# Generated by Django 5.0.7 on 2024-09-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
