# Generated by Django 5.0.7 on 2025-01-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_poll_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.RemoveField(
            model_name='poll',
            name='questions',
        ),
        migrations.AlterField(
            model_name='poll',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='poll',
            name='questions',
            field=models.ManyToManyField(default='[]', null=True, to='polls.question'),
        ),
    ]
