# Generated by Django 5.0.7 on 2025-01-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_choice_choice_text_remove_poll_questions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='questions',
            field=models.ManyToManyField(to='polls.question'),
        ),
    ]
